name: ✅ PR Code Checks
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM & Install dependencies
        uses: ./.github/actions/setup-pnpm

      - name: Track main branch
        run: git branch --track main origin/main

      - name: Check formatting
        run: pnpm nx format:check --all

      - name: 🧪 Lint, build and test affected projects
        run: pnpm nx affected --base=origin/main --target=lint,build,test --parallel=5
