name: Publish npm package

on:
    push:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
            - run: npm install --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    publish:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.4.0
              with:
                  node-version: 14
                  cache: 'npm'
                  registry-url: https://npm.pkg.github.com/
            - run: npm install --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
            - run: npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
